### ISSUE TITLE
add margins / make  barcode smaller

### ISSUE THREAD

**Issue by rubaboo** [CatimaLoyalty/Android#1019] opened 2022-09-12 00:17 UTC
Some store scanners have trouble reading the barcode because it's stretched to the entire width of the phone screen. Please add the ability to make the barcode smaller. The exact UX is not important ("zoom","margin width", whatever). The desired end result is a barcode comparable in size to the one on a real card, or a typical UPC on a packaged item. TY.

**Comment by rubaboo** [comment] 2022-09-12 16:14
The feature scales a QR code but not a barcode. Barcode remains full width. Most loyalty cards carry a barcode, not QR.

**Comment by TheLastProject** [comment] 2022-09-12 17:16
Thanks for your report. This seems like a duplicate of #788. I've added some extra info to that issue for whoever wants to tackle the issue (I really don't have the time to tackle every single issue myself currently).

**Closed by TheLastProject** 2022-09-12 17:16 UTC
