### ISSUE TITLE
material you issues

### ISSUE THREAD

**Issue by andsofine** [CatimaLoyalty/Android#918] opened 2022-06-27 18:29 UTC
I have a purple accent wallpaper installed, and in the app in some places (maybe only what is shown in the screenshots) is used red
![AFFIX_20220627_211749.png](https://user-images.githubusercontent.com/99369164/176009285-2bee8e6f-d29c-443e-9a5c-f96f45cbef2a.png)

and here the text color is not accented (as in the screenshot on the right)
![AFFIX_20220627_212356.png](https://user-images.githubusercontent.com/99369164/176010054-714b5421-4a07-4ea9-bda3-ae587b739f82.png)

**Comment by TheLastProject** [comment] 2022-06-27 21:04
Your first screenshots are weird because I had someone sent me screenshots from their Pixel phone and it definitely worked there with multiple different colours:

| | | |
| - | - | - |
| ![photo_2022-06-27_22-55-15](https://user-images.githubusercontent.com/1885159/176034062-9c629297-da31-4838-966a-fc840dce4993.jpg) | ![photo_2022-06-27_22-55-17](https://user-images.githubusercontent.com/1885159/176034065-385b4562-ebf3-437a-9a28-239384e9eedc.jpg) | ![photo_2022-06-27_22-55-18](https://user-images.githubusercontent.com/1885159/176034072-80316f65-1434-45fb-9f69-7aad366b0cfd.jpg) |

Maybe this is not a Catima but but a bug with your Android version or Google's Material Design library? Because the only thing Catima does is ask Google's library "hey, please apply the correct colours".

The fact that I'm overriding the button text colour here is a bug though, so I fixed that in 88d27c0385a962a428e5c0fde58a040b6b6b53ab.

The purple buttons I'm not sure about.

Did you set any theme in settings? Because setting a theme should override other stuff. Otherwise I'm pretty... unsure what is even going on here and given I can't test much (only have 1 emulator where it works and no real device) I don't think I can do much more than hope that a new release of https://github.com/material-components/material-components-android will fix stuff :(

**Comment by TheLastProject** [comment] 2022-06-28 21:21
So I was just looking at one of the Google Play Pre-launch reports and on one of the devices the random-clicking-bot changed theme colours and the theme colour change only applied to Catima screens different from the main screen:

https://user-images.githubusercontent.com/1885159/176289473-8b653d5f-7a40-4629-aabe-8919ab679800.mp4

It went as such:
1. App started on system theme
2. Theme changed to green around 0:30
3. Theme changed to blue around 0:52
4. Went back to home around 0:56 -> home screen did not properly refresh, still using red colours
5. Went to groups around 0:59 -> groups used correct colours
6. Went back to home around 1:06 -> home screen still using red colours
7. Went to scan screen around 1:07 -> scan screen used correct colours

Could it be this happened to you? That it's just a bug where it doesn't correctly change all colours after a theme change until restart?

**Comment by TheLastProject** [comment] 2022-06-29 18:29
Hmm, then I don't know how to reproduce this :(

**Comment by TheLastProject** [comment] 2022-06-29 19:43
Okay, it took me some time to understand and reproduce it because I thought this report was about Material You's dynamic colours, but it isn't, it's a bug with custom themes not applying to the main screen correctly.

Turned out we were installing the splash screen incorrectly. It wasn't documented well, but I managed to find a bit of documentations containing a note that helped me figure out what was wrong.

This should be fixed in c35fe166edffe369576f713898f4b6b2658dfa8a, thanks for your patience in trying to make me understand.

**Closed by TheLastProject** 2022-06-29 19:43 UTC
Labels: state: needs info
