### ISSUE TITLE
Request during import: do you want to replace the current ones or add to them?

### ISSUE THREAD

**Issue by Korb** [CatimaLoyalty/Android#1979] opened 2024-07-06 08:13 UTC
Since there is currently no two-way synchronization in the application, I decided to adhere to the rule between all devices using one database: all changes are made only on one device, which generates databases for other devices. However, the first time I tried to update the map database on one of the “secondary” devices, I encountered a problem. The fact is that the application does not provide a way to completely replace existing cards with imported cards. In fact, there is not even a way to select all the cards in order to delete them. I need to mark each card individually. If this is not done, all cards will be displayed in duplicate.

## Workaround

In the system settings of the "secondary" device, delete all user application data. Run it as if for the first time and import the new version of the map database. And also, manually return all application settings to the previous ones.

**Comment by TheLastProject** [comment] 2024-07-06 10:05
This seems to me like a duplicate of #512

**Closed by TheLastProject** 2024-07-06 10:05 UTC
