### ISSUE TITLE
Wear OS compability

### ISSUE THREAD

**Issue by 00svd00** [CatimaLoyalty/Android#1620] opened 2023-11-06 15:19 UTC
For now app is crashing with
`11-06 18:12:59.203   932   972 I ActivityTaskManager: Displayed me.hackerchick.catima/protect.card_locker.MainActivity: +663ms
11-06 18:12:59.248 22480 22480 D AndroidRuntime: Shutting down VM
11-06 18:12:59.250 22480 22480 E AndroidRuntime: FATAL EXCEPTION: main
11-06 18:12:59.250 22480 22480 E AndroidRuntime: Process: me.hackerchick.catima, PID: 22480
11-06 18:12:59.250 22480 22480 E AndroidRuntime: java.lang.IllegalStateException: android.os.ServiceManager$ServiceNotFoundException: No service published for: search
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at android.app.Activity.ensureSearchManager(Activity.java:6787)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at android.app.Activity.getSystemService(Activity.java:6801)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at protect.card_locker.MainActivity.onCreateOptionsMenu(MainActivity.java:575)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at android.app.Activity.onCreatePanelMenu(Activity.java:4206)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:521)
nCreatePanelMenu(FragmentActivity.java:287)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3429)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
tyThread.java:7651)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: Caused by: android.os.ServiceManager$ServiceNotFoundException: No service published for: search
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at android.os.ServiceManager.getServiceOrThrow(ServiceManager.java:153)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at android.app.SearchManager.<init>(SearchManager.java:560)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	at android.app.Activity.ensureSearchManager(Activity.java:6785)
11-06 18:12:59.250 22480 22480 E AndroidRuntime: 	... 16 more
=0x2
11-06 18:12:59.253   932  7574 W ActivityTaskManager:   Force finishing activity me.hackerchick.catima/protect.card_locker.MainActivity`

**Comment by TheLastProject** [comment] 2023-11-06 18:25
Duplicate of #25

**Closed by TheLastProject** 2023-11-06 18:25 UTC
