### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by powerriegel** [CatimaLoyalty/Android#1387] opened 2023-06-23 07:46 UTC
Hello,

switching from Huawei Mate 10 Pro to Samsung S23 Ultra, I've observed two issues when using the import feature of Catima 2.24.2. One seems to be quite severe, the other is easy to work around.

# Importing mixes imports with existing datasets

If you have a couple of records with multiple images stored and then importing, the result is that the imported records are somewhat mixed within the existing datasets. I noticed this by viewing the images of one record. One image was original, the other was imported and overwrote the second original image.

# Importing from nextcloud crashes the app.

The app repeatedly crashed when trying to import from a nextcloud share in Android 13. Exporting to such a share in Android 10 was no problem. To work around this, users can save the catima.zip to their Downloads folder and then import works.

**Comment by obfusk** [comment] 2023-06-23 08:51
>  Importing mixes imports with existing datasets

Unfortunately, this is a known limitation of the current importer.
We're working on improving that, but it will probably mean dropping existing data before importing.
I am considering creating an external tool to merge two exported datasets if there's a demand for that functionality.
See #1343.

**Comment by obfusk** [comment] 2023-06-23 18:33
>  I am considering creating an external tool to merge two exported datasets if there's a demand for that functionality.

https://github.com/obfusk/catimerge

**Comment by TheLastProject** [comment] 2023-06-23 19:18
> Importing from nextcloud crashes the app.

I can't reproduce this. Can you please list step-by-step exactly everything you do and click?

**Comment by TheLastProject** [comment] 2023-06-23 19:19
> Importing mixes imports with existing datasets

Would be fixed by #1343 but that's still WIP

**Comment by obfusk** [comment] 2023-06-26 15:21
> Importing mixes imports with existing datasets

#1394 should properly merge both datasets.

**Comment by powerriegel** [comment] 2023-06-28 08:22
> > Importing from nextcloud crashes the app.
> 
> I can't reproduce this. Can you please list step-by-step exactly everything you do and click?

I exported a catima.zip on my old phone (Android 10) and stored it to nextcloud. Then, I switched to my new Android 13 phone (Samsung S23).  Pointed the three dots in the upper right corner > Import/Export > Choose from file system  > Catima > Ok. Now, we are in the file manager. 

Click the burger menu in top left corner, scroll down to nextcloud and click catima.zip. No "importing" box appears. No import is being done. One time Catima crashed, too. I think the problem is here to locate the file in the file system.

**Comment by TheLastProject** [comment] 2023-06-29 13:02
Thanks for the info. Looking more at everything and with the extra data, this issue is a duplicate of multiple existing issues:

Importing mixes imports with existing datasets: This is a duplicate of #512.

Importing from nextcloud crashes the app: This is a duplicate of #513.

Both issues still need to be fixed, but to keep the issue tracker easier to read I'll close this in favor of those two issues.

**Closed by TheLastProject** 2023-06-29 13:02 UTC
Labels: state: needs info

**Comment by obfusk** [comment] 2023-07-17 19:58
@powerriegel #1422 was just merged; importing will no longer mix datasets (but can sometimes result in duplicates).
