### ISSUE TITLE
NFC support

### ISSUE THREAD

**Issue by Shahin-rmz** [CatimaLoyalty/Android#888] opened 2022-05-26 18:48 UTC
Hello, I recently found the app and installed it.
Thanks for providing secure and open source app for the world.
I want to know if the app supports NFC and how may I use it?
Thanks

**Comment by Altonss** [comment] 2022-05-26 18:51
Hello, thanks for using Catima!
This issue is a duplicate of https://github.com/CatimaLoyalty/Android/issues/166 and the answer is: support for NFC is not planned for the foreseeable future.

**Comment by Shahin-rmz** [comment] 2022-05-26 18:56
Thanks for reply.
Read the thread, it's interesting though.
Any idea about how can I use loyality cards which only works via NFC?
P.S I am not very comfortable with Google Services and propriety apps.

**Closed** 2022-05-26 18:57 UTC

**Comment by Altonss** [comment] 2022-05-26 18:59
> Any idea about how can I use loyality cards which only works via NFC?

No I don't have any idea, and probably there is no way (at least no easy way).

**Comment by TheLastProject** [comment] 2022-05-26 19:26
I wish it was possible, but sadly these NFC cards aren't things you can just copy. If it was possible, I would've loved to use Catima for my bank stuff too because they're now forcing Google Play. But sadly, not possible :(
