### ISSUE TITLE
Export is aborted when the phone is rotated

### ISSUE THREAD

**Issue by guy-teube** [CatimaLoyalty/Android#1715] opened 2024-01-30 14:37 UTC
Steps to reproduce:
1. Run an export from the parameters of the app, choose a password and a directory
2. During the export, rotate the phone (it has to be allowed in the parameters of the phone)
3. Catima closes the export loading spinner, and displays the Import/export screen. No file is generated.

Expected result: 
The export file should be run until the end regardless of orientation of the phone, and the export file should be generated

Reproduced with 2.26.0 version, on Android 13

**Comment by TheLastProject** [comment] 2024-01-30 17:59
This is kind of a duplicate of #513 (it's the same issue), but I guess this specific case could be worked around by force-disabling rotation in the import/export activity to reduce the risk of accidental cancellations.

Of course #513 does still need to be fixed too.

**Comment by TheLastProject** [comment] 2024-02-07 18:21
I implemented a workaround in d24366a3ba17bea17c1536f2083a7b615ea5b1f4 by locking the orientation in the ImportExportActivity. It's hacky, but not being able to rotate the screen is less bad than the import/export failing

**Closed by TheLastProject** 2024-02-07 18:21 UTC
Labels: type: bug, good first issue, severity: critical, common: occasional
