### ISSUE TITLE
Thumbnails with transparent are unreadable

### ISSUE THREAD

**Issue by mingyee2** [CatimaLoyalty/Android#2199] opened 2024-11-28 22:50 UTC
If I set the thumbnail of a card, the background colour for the card automatically changes to the dominant colour of the thumbnail. The problem is if the thumbnail has a transparent background, such as for Boots (below). Then the background is basically the same colour as the text of the logo, which makes the thumbnail completely unreadable on the home screen.
![image](https://github.com/user-attachments/assets/0de9ad57-ab08-481e-a267-023e157bc546)

**Comment by TheLastProject** [comment] 2024-11-28 23:03
Thanks for reporting it. Yeah, that's definitely an issue that needs fixing. I've just not had the time to deal with it.

This issue is a duplicate of #1972, I've updated #1972's title to make it more descriptive.

**Closed by TheLastProject** 2024-11-28 23:03 UTC
