### ISSUE TITLE
Expiry dates - (only sometimes) red?

### ISSUE THREAD

**Issue by cpy82** [CatimaLoyalty/Android#1049] opened 2022-09-26 15:54 UTC
Hello,
maybe I haven't understood it yet, but why are the same dates sometimes red and sometimes not?
Did I miss something?

Thanks!

![2](https://user-images.githubusercontent.com/97791051/192322997-2433fdfa-1ad2-4e47-b3bf-462f2dfb62fb.png)

![1](https://user-images.githubusercontent.com/97791051/192323006-8843abf7-a0a3-458e-a774-21d3bde080a2.png)

**Comment by TheLastProject** [comment] 2022-09-26 17:08
It's supposed to be red if the expiry is in the past (so: the card has expired).

It surprises me to see the same date everywhere though. Did you edit this picture in any way? I've never ran into a bug with expiry not always turning red before.

If these dates aren't edited, could you please give me some more info (Catima version, Android version, phone model)?

**Comment by TheLastProject** [comment] 2022-09-26 21:20
Really weird. Labelling it as "unconfirmed" because I can't reproduce it on my device.

Could you maybe share an export? You can share just the .csv and just rename every name and code to "test" or something. Really unsure what's going on here.

**Comment by TheLastProject** [comment] 2022-10-15 12:34
Looking more closely, this is actually a fairly simple RecyclerView bug and I can't believe I didn't realize this.

Android's RecyclerView is optimized for many layouts that look the same by basically just re-using the old layout. However, this can cause it to re-use the old state. This bug here was caused by me setting the text colour to red sometimes but never explicitly setting it to not red:

https://github.com/CatimaLoyalty/Android/blob/b13aaacdfff952983810fa8f288866834892a230/app/src/main/java/protect/card_locker/LoyaltyCardCursorAdapter.java#L331

This will be fixed by #1088.

**Comment by TheLastProject** [comment] 2022-10-16 15:15
My PR ended up not fixing this completely somehow. I can reproduce it as follows:

1. Create a new card with expiry set to yesterday (so it's expired)
2. Notice the red colour on both clock and text
3. In the edit screen, change the expiry to a date in the future (so it's no longer expired)
4. Notice how the clock is correctly white, but the text is still red

Still pretty sure this is a RecyclerView bug, but not completely sure how my PR didn't fix this.

**Closed** 2022-10-24 17:13 UTC
Labels: type: bug, severity: major, common: occasional
