### ISSUE TITLE
NFC support?

### ISSUE THREAD

**Issue by parabolapersuader** [CatimaLoyalty/Android#746] opened 2022-01-15 06:56 UTC
NFC cards are becoming more common, and NFC phones as well. Could you add NFC card support?

**Comment by TheLastProject** [comment] 2022-01-15 08:52
Duplicate of #166 and #668.

**Closed by TheLastProject** 2022-01-15 08:52 UTC
Labels: duplicate

**Comment by parabolapersuader** [comment] 2022-01-15 09:21
Not as in Google Pay, but as in my library card which is quite a static thing, like the barcode.

**Comment by TheLastProject** [comment] 2022-01-15 09:23
What is written in #166 still stands.
