### ISSUE TITLE
Migrate codebase to Kotlin

### ISSUE THREAD

**Issue by criticalAY** [CatimaLoyalty/Android#2004] opened 2024-07-17 20:37 UTC
Hey @TheLastProject  I propose migrating the codebase to Jetpack or at least Kotlin. We can offer much better UI/UX with compose?

**Comment by TheLastProject** [comment] 2024-07-19 15:22
I'm not opposed to Kotlin and Jetpack, they seem good technologies. While I'm generally hesitant to adopt brand-new Google technologies due to their track record of abandoning things, I think both have been around for long enough that it seems unlikely Google will drop support for either any time soon.

However, at the end of the day, the problem is simply that I maintain Catima basically alone (aside from the occasionally small contributed patch here and there) and have a full-time job and other things to deal with which severely limits my time. And I'd rather focus on fixing bugs and adding features people want than rewrite working code (in this case from Java to Kotlin or Android XML Layouts to Jetpack Compose).

I also simply have more experience with Java and Android XML code, which makes them easier for me to maintain than Kotlin and Jetpack Compose currently (I have some small Kotlin experience but not a lot and I don't have any Jetpack Compose experience at all), meaning I can fix bugs and add new features faster and more reliably with Java and Android XML. I'm sure that Kotlin and Jetpack Compose could be just as fast or even faster after getting more used to them, but I'm simply not there yet.

I think "rewriting Catima" is a bit of a tall order and while I know Android offers tooling to translate Java code to Kotlin code, automatic code translation like that is something I'm quite careful with because it does mean I'll have to relearn my own codebase.

So I'm going to close this issue as "wontfix". Not because I'm opposed to it, but because it's just a lot of work that I don't really think I have time for and that, at least at first, will cost more than it causes benefits.

However, if you see specific areas where rewriting some code has explicit improvements (think: faster, better maintainability, etc.) and are willing to spend time answering questions from me on how stuff works and why specific decisions were made some rewriting may be possible. But again, I have quite limited time so that will be... rough, at best :)

**Closed by TheLastProject** 2024-07-19 15:22 UTC
