### ISSUE TITLE
Dark Theme issue

### ISSUE THREAD

**Issue by galen1423** [CatimaLoyalty/Android#1361] opened 2023-06-10 09:28 UTC
Hi,

First of all thank you for this very useful application. I post two screenshots which show that in dark mode, some boxes remain dark...
With the light theme, we see the names correctly. I noticed this bug since the last update (2.23.3). I installed Catima using Fdroid on a OnePlus Nord 2 device with OxygenOS 12.1 (Android 12).

Thanks again for your work & I hope this bug will be solved.

![Screenshot_2023-06-10-11-04-07-49_0e0fb5e4c7b0c70cd406dc034ad65059](https://github.com/CatimaLoyalty/Android/assets/24211031/7b5250eb-2309-4aef-9441-bf4e893d79e1)

![Screenshot_2023-06-10-11-09-09-55_0e0fb5e4c7b0c70cd406dc034ad65059](https://github.com/CatimaLoyalty/Android/assets/24211031/21cbd5ec-1f53-4ffb-96c9-840e76d30525)

**Comment by TheLastProject** [comment] 2023-06-10 10:30
This is super confusing, it looks like your cards have no colour assigned to them? I have no clue how that could possibly happen.

Can you email me an export of your data?

**Comment by galen1423** [comment] 2023-06-10 11:24
I have send you my export data.

**Comment by TheLastProject** [comment] 2023-06-10 11:28
Thanks, I can confirm my suspicion with this, `headercolor` is not set for most of your cards. I'm going to work on making Catima deal with that (unexpected) situation more gracefully.

**Closed** 2023-06-10 16:34 UTC
Labels: type: bug, severity: critical, common: uncommon

**Comment by galen1423** [comment] 2023-06-15 09:52
Thanks for fix. Now, it's working at new with version 2.24.1.
