### ISSUE TITLE
Exporting does not work

### ISSUE THREAD

**Issue by wjg57** [CatimaLoyalty/Android#488] opened 2021-10-12 10:27 UTC
At least on Android 10 exporting does not work, because the file exported is not a media file (.zip is not media), but the requested file system permissions are for media files only.

**Comment by TheLastProject** [comment] 2021-10-12 10:32
It works for me on Android 11. Are you sure this is not just a duplicate of https://github.com/TheLastProject/Catima/issues/486? What version did you test this on?

**Closed as completed** 2021-10-13 10:16 UTC
Labels: state: duplicate
